name: build
on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Simulate Audio Device
        shell: powershell
        run: |
          Start-Service audio*
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
          Expand-7ZipArchive -Path C:\Scream3.6.zip -DestinationPath C:\Scream
          $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
          $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()
          cd C:\Scream\Install\driver
          C:\Scream\Install\helpers\devcon install Scream.inf *Scream
      - name: Check Audio Device
        shell: powershell
        run: Get-CimInstance Win32_SoundDevice | fl *
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: make git mingw-w64-x86_64-gcc mingw-w64-x86_64-portaudio
      - name: Build and Install Modules
        run: |
          for n in {audio,graphics,io,math}; do
              git clone https://github.com/pazvirtual/paz_${n}.git
              make -C paz_${n} -j
              make -C paz_${n} install
          done
      - name: Build and Test
        run: make -j
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            libpazengine.a
            test/test.exe
#  macos:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install cmake xorg-dev xvfb portaudio19-dev
          curl -LO https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.zip
          unzip glfw-3.4.zip
          cd glfw-3.4
          cmake -S . -B build -D GLFW_BUILD_WAYLAND=0
          cd build
          make
          sudo make install
      - name: Simulate Display
        run: Xvfb &
      - name: Simulate Audio Device
        run: |
          sudo apt install pulseaudio
          pulseaudio --start
      - name: Check Audio Device
        run: pactl list short
      - name: Build and Install Modules
        run: |
          export DISPLAY=:0
          for n in {audio,graphics,io,math}; do
              git clone https://github.com/pazvirtual/paz_${n}.git
              make -C paz_${n} -j
              sudo make -C paz_${n} install
          done
      - name: Build and Test
        run: |
          export DISPLAY=:0
          make -j
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            libpazengine.a
            test/test
